<div class="top-edit">
  <h3 class="DispTitle">
    会員公開リストに参加する
  </h3>
</div>
<br>
<table border="0">
  <tr>
    <td align="left">
      <font size="4" color="darkorange">
        <strong>【会員公開リストに参加する】</strong>
      </font>
    </td>
  </tr>
  <tr>
    <td align="left">
      <font size="2" color="#ff0000">
        ※「ご注意：Internet Explorerのバージョンが「6.0SP1」以下の場合は送信することができません。」
      </font>
    </td>
  </tr>
  <tr>
    <td align="left">
      <br>
      下のフォームに表示された内容が現在のご登録内容です。<br>
      内容確認の結果、変更がない場合は「キャンセス」で終了してください。<br>
      内容を変更する場合は、変更箇所をプルダウンで選択するか、表示内容の上から直接変更し、最後に「更新」で終了してください。<br>
      <br>
    </td>
  </tr>
</table>
