<div class="top-edit">
  <h3 class="DispTitle">
    代理人申請
  </h3>
</div>
<br>
<table border="0">
  <tr>
    <td align="left">
      <span style="font-size:14pt; font-weight:bold; color:#8b4513;">
        ■代理人申請
      </span>
    </td>
  </tr>
  <tr>
    <td align="left">
      　代表者に代わって、代理の方が会からの通知の受信を行ったり、<br>
      　会員ログイン（マイページ）て代表者の情報を代わって管理する場合の申請です。<br>
      <br>
    </td>
  </tr>
</table>
