<table width="980" align="center" cellpadding="0" border="0" border="0" >
 <tr>
  <td>
   <div align="left"><span style="font-size: 14pt;color: #ff6600">
     <STRONG>■社会貢献活動</STRONG>
     </span><BR> <span style="font-size: 11pt">&nbsp;
○○法人会では、○○委員会を通じて次の社会貢献活動に参加することができます。<BR>
一企業では出来ない活動も、渋谷法人会会員が協力することで可能となる活動です。<BR>
□□□<BR><BR>

下のフォームに表示された内容が現在のご登録内容です。<br>
内容確認の結果、変更が無い場合は「キャンセル」で終了します。<br>
内容を変更する場合は、変更箇所のすべてを表示内容の上から直接変更し、最後に「更新」で更新します。<br>
また、会員登録を解除したい場合は、右下の「登録解除」をクリックしてください。<br>
</span>
</div>

   
  </td>
 </tr>
</table>

